clear:
	rm -rf *.o *.a *_test

check_fmt:
	clang-format -style=LLVM --dry-run --Werror $$(find . -name "*.c" -o -name "*.h")

fmt:
	clang-format -style=LLVM -i $$(find . -name "*.c" -o -name "*.h")

# --- task4 (quadratic)
quadratic.o: quadratic.h quadratic.c
	gcc -g -c quadratic.c -o quadratic.o

quadratic.a: quadratic.o
	ar rc quadratic.a quadratic.o

quadratic_test.o: quadratic_test.c
	gcc -g -c quadratic_test.c -o quadratic_test.o

quadratic_test: quadratic_test.o quadratic.a
	gcc -g -static -o quadratic_test quadratic_test.o quadratic.a

# --- task5 (integr)
task5.o: task5/include/integr.h task5/src/integr.c
	gcc -g -c task5/src/integr.c -o task5.o

task5.a: task5.o
	ar rc task5.a task5.o

task5_test.o: task5/src/test5.c
	gcc -g -c task5/src/test5.c -o task5_test.o

task5_test: task5_test.o task5.a
	gcc -g -static -o task5_test task5_test.o task5.a

# --- task6
task6.o: task6/include/task6.h task6/src/task6.c
	gcc -g -c task6/src/task6.c -o task6.o

task6.a: task6.o
	ar rc task6.a task6.o

task6_test.o: task6/src/test.c
	gcc -g -c task6/src/test.c -o task6_test.o

task6_test: task6_test.o task6.a
	gcc -g -static -o task6_test task6_test.o task6.a

# --- task7 (stack)
task7.o: task7/include/stack.h task7/src/stack.c
	gcc -g -c task7/src/stack.c -o task7.o

task7.a: task7.o
	ar rc task7.a task7.o

task7_test.o: task7/src/test.c
	gcc -g -c task7/src/test.c -o task7_test.o

task7_test: task7_test.o task7.a
	gcc -g -static -o task7_test task7_test.o task7.a

# --- test
test: quadratic_test task5_test task6_test task7_test
	./quadratic_test
	./task5_test
	./task6_test
	./task7_test
