clean:
	rm -f *.o *.a *_test *.out

check_fmt:
	clang-format -style=LLVM --dry-run --Werror $$(find . -name "*.c" -o -name "*.h")

fmt:
	clang-format -style=LLVM -i $$(find . -name "*.c" -o -name "*.h")

test:
	@files=$$(ls *.c | grep -v "_test.c"); \
	for test_file in *_test.c; do \
		executable=$${test_file%.c}; \
		gcc -Wall -Wextra -Werror $$test_file $$files -o $$executable; \
	done
	@for test_bin in *_test; do \
		echo "Running: $$test_bin"; \
		./$$test_bin; \
	done
